### ISSUE TITLE
pip cant install check50

### ISSUE THREAD

**Issue by broccolihht** [cs50/check50#152]
```
  Running setup.py install for bs4 ... done
  Running setup.py install for termcolor ... done
  Running setup.py install for submit50 ... done
  Running setup.py install for check50 ... error
    ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2j/h5ng9w_d3qng1n8wdqjr1krm0000gn/T/pip-install-wi0kbopz/check50/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2j/h5ng9w_d3qng1n8wdqjr1krm0000gn/T/pip-record-d13kxinq/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2j/h5ng9w_d3qng1n8wdqjr1krm0000gn/T/pip-install-wi0kbopz/check50/setup.py", line 62, in <module>
        version="2.2.6"
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/2j/h5ng9w_d3qng1n8wdqjr1krm0000gn/T/pip-install-wi0kbopz/check50/setup.py", line 22, in run
        raise RuntimeError("Error installing certificates.")
    RuntimeError: Error installing certificates.
    ----------------------------------------
ERROR: Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2j/h5ng9w_d3qng1n8wdqjr1krm0000gn/T/pip-install-wi0kbopz/check50/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2j/h5ng9w_d3qng1n8wdqjr1krm0000gn/T/pip-record-d13kxinq/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2j/h5ng9w_d3qng1n8wdqjr1krm0000gn/T/pip-install-wi0kbopz/check50/
```

**Comment by broccolihht** [comment]
whats the problem?

**Comment by broccolihht** [comment]
on mac

**Comment by crossroads1112** [comment]
This is fixed in check50 v3 which will be released (hopefully) by the end of the month.
