### ISSUE TITLE
commit.gpgSign causes an error with uploads

### ISSUE THREAD

**Issue by Douile** [cs50/check50#253]
If a user has `commit.gpgSign` set to true in their global git config check50 will error when trying to upload.

```
Traceback (most recent call last):
  File "/home/tom/.local/bin/check50", line 33, in <module>
    sys.exit(load_entry_point('check50==3.2.2', 'console_scripts', 'check50')())
  File "/home/tom/.local/lib/python3.9/site-packages/check50/__main__.py", line 336, in main
    commit_hash = lib50.push("check50", internal.slug, internal.CONFIG_LOADER, data={"check50": True})[1]
  File "/home/tom/.local/lib/python3.9/site-packages/lib50/_api.py", line 73, in push
    username, commit_hash = upload(slug, user, tool, data)
  File "/home/tom/.local/lib/python3.9/site-packages/lib50/_api.py", line 354, in upload
    _run(git("commit -m {msg} --allow-empty", msg=commit_message))
  File "/home/tom/.local/lib/python3.9/site-packages/lib50/_api.py", line 704, in _run
    command_output = child.read().strip().replace("\r\n", "\n")
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/home/tom/.local/lib/python3.9/site-packages/lib50/_api.py", line 697, in _spawn
    raise Error()
lib50._errors.Error
Sorry, something is wrong! check50 ran into an error.
Please let CS50 know by emailing the error above to sysadmins@cs50.harvard.edu.
```

**Comment by Douile** [comment]
^ Should be fixable by just adding `--no-gpg-sign` to the git args
