### ISSUE TITLE
Error installing certificates on Mac

### ISSUE THREAD

**Issue by tlively** [cs50/check50#61]
The following error is the result of running `pip3 install check50` on MacOS 10.12 with  `pip3 --version` giving `pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)`. Sudo does not fix this issue. 
```
Collecting check50
Requirement already satisfied: pexpect in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: backports.shutil-which in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: argparse in /usr/local/lib/python3.6/site-packages (from check50)
Collecting submit50 (from check50)
  Using cached submit50-2.4.2.tar.gz
Requirement already satisfied: termcolor in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/site-packages (from pexpect->check50)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: backports.shutil_get_terminal_size in /usr/local/lib/python3.6/site-packages (from submit50->check50)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from submit50->check50)
Building wheels for collected packages: submit50
  Running setup.py bdist_wheel for submit50 ... error
  Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/tmpfdyanzvdpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying submit50.py -> build/lib
  installing to build/bdist.macosx-10.12-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/setup.py", line 65, in <module>
      version="2.4.2"
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/setup.py", line 22, in run
      raise RuntimeError("Error installing certificates.")
  RuntimeError: Error installing certificates.

  ----------------------------------------
  Failed building wheel for submit50
  Running setup.py clean for submit50
Failed to build submit50
Installing collected packages: submit50, check50
  Running setup.py install for submit50 ... error
    Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-7j2ug69l-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/setup.py", line 65, in <module>
        version="2.4.2"
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/setup.py", line 22, in run
        raise RuntimeError("Error installing certificates.")
    RuntimeError: Error installing certificates.

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-7j2ug69l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-dvp6y9e4/submit50/

**Comment by tlively** [comment]
On the other hand, `pip install check50` works correctly inside the cli50 container.

**Comment by crossroads1112** [comment]
@daveyproctor didn't you have this issue a while back? Do you remember what we did to fix it?

**Comment by daveyproctor** [comment]
@crossroads1112 I still have the same error (just retried). @kzidane set up `virtualenv` for me, which has solved countless other problems, but not this one! Even within the virtual environment, I get the same error.

**Comment by kzidane** [comment]
@tlively @daveyproctor should be fixed now!

**Comment by tlively** [comment]
@kzidane I'm getting this error again. I just noticed now because I've been using cli50 so this hasn't been a problem, but now I need to develop locally so I tried to install check50 again. The entire output is below.
```
Thomass-MacBook-Pro:CS50_2017 thomas$ pip3 install check50
Collecting check50
  Using cached check50-2.0.4.tar.gz
Requirement already satisfied: argparse in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: pexpect in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: backports.shutil_which in /usr/local/lib/python3.6/site-packages (from check50)
Requirement already satisfied: termcolor in /usr/local/lib/python3.6/site-packages (from check50)
Collecting submit50 (from check50)
  Using cached submit50-2.4.3.tar.gz
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/site-packages (from pexpect->check50)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->check50)
Requirement already satisfied: backports.shutil_get_terminal_size in /usr/local/lib/python3.6/site-packages (from submit50->check50)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from submit50->check50)
Building wheels for collected packages: check50, submit50
  Running setup.py bdist_wheel for check50 ... error
  Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/check50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/tmp2x2v_w7lpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying check50.py -> build/lib
  copying config.py -> build/lib
  installing to build/bdist.macosx-10.12-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/check50/setup.py", line 63, in <module>
      version="2.0.4"
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 240, in run
      self.run_command('install')
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/check50/setup.py", line 22, in run
      raise RuntimeError("Error installing certificates.")
  RuntimeError: Error installing certificates.

  ----------------------------------------
  Failed building wheel for check50
  Running setup.py clean for check50
  Running setup.py bdist_wheel for submit50 ... error
  Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/tmp8q3jzbw7pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying submit50.py -> build/lib
  installing to build/bdist.macosx-10.12-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/setup.py", line 65, in <module>
      version="2.4.3"
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 240, in run
      self.run_command('install')
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/setup.py", line 22, in run
      raise RuntimeError("Error installing certificates.")
  RuntimeError: Error installing certificates.

  ----------------------------------------
  Failed building wheel for submit50
  Running setup.py clean for submit50
Failed to build check50 submit50
Installing collected packages: submit50, check50
  Running setup.py install for submit50 ... error
    Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-qhh05h77-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/setup.py", line 65, in <module>
        version="2.4.3"
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/setup.py", line 22, in run
        raise RuntimeError("Error installing certificates.")
    RuntimeError: Error installing certificates.

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-qhh05h77-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rz/ts_f_9513jz8q7xrwrhbtx5h0000gn/T/pip-build-ppd8ei1k/submit50/
```

**Comment by tlively** [comment]
Created new more specific issue at #71
