### ISSUE TITLE
pset3 find check don't work

### ISSUE THREAD

**Issue by Petar-np** [cs50/check50#68]
When I run `check50 cs50/2017/x/find/more` I get this output
```
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/bin/check50", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```
Not sure why, it worked three or four months ago when I finished this task. I didn't submit it because I wanted to finish game of fifteen too and to submit both. I came back today to finish it and I had to do update50, so maybe that is a reason for this problem. Also, pset3 find didn't work until I run make all again and recompiled it.

**Comment by Petar-np** [comment]
Everything is normal after refresh
