### ISSUE TITLE
exception when running check50 locally more than once

### ISSUE THREAD

**Issue by kzidane** [cs50/check50#79]
```
~/workspace/hello/ $ check50 --local cs50/2017/fall/hello
:) hello.c exists.
:( hello.c compiles.
    expected exit code 0, not 1
:| prints "hello, world\n"
    can't check until a frown turns upside down
~/workspace/hello/ $ check50 --local --verbose cs50/2017/fall/hello                                               
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/bin/check50", line 11, in <module>
    load_entry_point('check50==2.1.0', 'console_scripts', 'check50')()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/check50.py", line 135, in main
    copy(filename, src_dir)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/check50.py", line 177, in copy
    shutil.copytree(src, os.path.join(dst, os.path.basename(src)))
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('~/.local/share/check50/cs50/checks/cs50/2017/ap/resize/more/check50', '/tmp/tmpf5p0pu92/_/~/.local/share/check50/cs50/checks/cs50/2017/ap/resize/more/check50', "[Errno 2] No such file or directory: '~/.local/share/check50/cs50/checks/cs50/2017/ap/resize/more/check50'"), ('~/.local/share/check50/cs50/checks/cs50/2017/ap/resize/less/check50', '/tmp/tmpf5p0pu92/_/~/.local/share/check50/cs50/checks/cs50/2017/ap/resize/less/check50', "[Errno 2] No such file or directory: '~/.local/share/check50/cs50/checks/cs50/2017/ap/resize/less/check50'"), ('~/.local/share/check50/cs50/checks/cs50/2017/ap/find/more/check50', '/tmp/tmpf5p0pu92/_/~/.local/share/check50/cs50/checks/cs50/2017/ap/find/more/check50', "[Errno 2] No such file or directory: '~/.local/share/check50/cs50/checks/cs50/2017/ap/find/more/check50'"), ('~/.local/share/check50/cs50/checks/cs50/2017/ap/find/less/check50', '/tmp/tmpf5p0pu92/_/~/.local/share/check50/cs50/checks/cs50/2017/ap/find/less/check50', "[Errno 2] No such file or directory: '~/.local/share/check50/cs50/checks/cs50/2017/ap/find/less/check50'")]
```

**Comment by kzidane** [comment]
Removing `~/` from the current directory (in this case `~/workspace/hello/`) seems to fix!

**Comment by dmalan** [comment]
@kzidane can this be closed now?

**Comment by kzidane** [comment]
Yes.
